

# Application name
spring.application.name=recruitment-requisition-service

# Server port
#server.port=8005
server.port=${SERVER_PORT:8001}

# Eureka client

#eureka.client.service-url.defaultZone=http://localhost:8087/registry-service/eureka/
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false






#it is always false
spring.cloud.compatibility-verifier.enabled=false




# Local DB configuration
#spring.datasource.url=jdbc:postgresql://103.147.56.152:5432/rms_db
#spring.datasource.username=rms_user
#spring.datasource.password=rms_user@321

#dynamic CI/CD for lcoal db
spring.datasource.url=jdbc:postgresql://${DB_HOST:103.147.56.152}:${DB_PORT:5432}/${DB_NAME:rms_db}
spring.datasource.username=${DB_USER:rms_user}
spring.datasource.password=${DB_PASSWORD:rms_user@321}

# live UAT  DB configuration
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/rms_db
#spring.datasource.username=rms_user
#spring.datasource.password=rms_user@321

#Live remote DB configuration
#spring.datasource.url=jdbc:postgresql://202.59.140.53:5432/rms_db
#spring.datasource.username=rms_remote_user
#spring.datasource.password=rms_remote_user@321

# Jpa/Hibernate configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#file.upload-dir=uploads
file.upload-dir=${FILE_UPLOAD_PATH:uploads}


#Local
#app.host-url=http://172.30.48.171:8005

app.host-url=${APP_HOST_URL:http://172.30.48.68:8001}

#Live
#app.host-url=http://202.59.140.53:8081/recruitment-requisition-service


# Swagger UI enable kora
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

 springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Static resource handling fix
#spring.mvc.static-path-pattern=/**




